### PR TITLE
Graphs

### PR DESCRIPTION
**Pull request by lzhang124**

### CODE REVIEW

**Review by mflauer — COMMENTED** [review]
Things that I think should be true about our graph visualization after looking at this dummy data graph: 
- no big dots at data points
- straight lines connecting data points
- color coordinate rather than having any sort of explicit text label
- minimal date labeling

**Comment by lzhang124** [comment]
and hover, but we can get to that last

**Comment by eemartin42** [comment]
I removed dots and text label--will work on the date formatting and color coding

**Comment by eemartin42** [comment]
Things done:
- added apple & google price data to compare graph
- added basic hover functionality on dummy data in volume graph
- made lines straight
TODO:
- add data to compare graph in percent change
- fix volume / portfolio graphs once we get the data
- finish making the function that dynamically changes the graph with the timescale
- color-coding graph lines
- fix date labeling

**Comment by eemartin42** [comment]
oh and company page graphs: those can be just raw prices v. time

**Comment by lzhang124** [comment]
OKAY sorry big change:

- Integrated liz's plot code into the rest of the workflow so you can add/remove plots
- Added portfolio data handling for visualizing portfolio plots

Biggest things still to do

- [ ] hovering on plot should get date (liz has basic code for this at the bottom of main.js - it's commented out for now, but just need to integrate it)
- [ ] hovering on a button/list/line should emphasize the respective components of that company (i.e. add a styling class)
- [ ] value plot for portfolio

**Review by mflauer — APPROVED** [review]

**Pull request merged**
